name = "kan"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[build]
command = "cd ../.. && pnpm build"

[[env.production.vars]]
NODE_ENV = "production"

[[env.preview.vars]]
NODE_ENV = "development" 